name: life_line_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.3
  url_launcher: ^6.2.5
  flutter_riverpod: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logos/
    - assets/images/
  
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
    - family: OpenSansItalic
      fonts:
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
    - family: OpenSansVariable
      fonts:
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf
